### ISSUE TITLE
Maximise checks against a suggestion up-front

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#225] opened 2018-07-05 10:58 UTC
Currently, a user can work through the workflow for a suggestion only to be told at the end of the process that the information provided in the suggestion already matches what's in Wikidata (thought the source URL might be new).

To help users focus their attention on adding new information into Wikidata, it would be helpful to somehow be able to do those checks at the start of the workflow so as not 'waste' a user's time confirming what is already there.

**Comment by tmtmtmtm** [comment] 2018-07-05 11:02
@rich-cassidy this seems like a duplicate of #181 — if there's anything additional here, perhaps worth adding as a comment to that.

**Closed by tmtmtmtm** 2018-07-05 11:02 UTC
Labels: verification via wikipedia
