### ISSUE TITLE
If a statement is both reconciled AND verified, automatically add info to Wikidata

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#227] opened 2018-07-05 11:06 UTC
Currently users have to manually choose to update Wikidata with the information in the suggestion once it's been verified and reconciled to WIkidata ID(s). Some efficiency gains could be made by automatically fulfilling this step once a suggestion is both reconciled and verified.

**Comment by tmtmtmtm** [comment] 2018-07-05 11:10
@rich-cassidy this looks like a duplicate of #180

**Closed by tmtmtmtm** 2018-07-05 11:10 UTC
Labels: verification via wikipedia
