### ISSUE TITLE
When adding new people to Wikidata, should add 'instance of: human'

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#145] opened 2018-06-21 19:01 UTC
This may not be necessary, but Wikidata shows a little tooltip on the new politicians I've been adding to Wikidata via the verification-pages - the tooltip basically says anything with a 'P39: position held' should be an 'instance of' a human (or other things, but human is what we want here).

**Comment by gbp** [comment] 2018-06-22 08:16
Duplicate of #60

**Closed by gbp** 2018-06-22 08:16 UTC
