### ISSUE TITLE
'Create <person name>' button not working at the reconcile step

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#169] opened 2018-06-27 20:47 UTC
![image](https://user-images.githubusercontent.com/35226004/41998815-931bb700-7a53-11e8-9b91-c37e8ff5777b.png)

The button just isn't doing anything.

Encountered whilst verifying the Deputies of Sicily and the Regional Councillors for Milan.

**Comment by rich-cassidy** [comment] 2018-06-28 11:20
Create button worked on this verification-page: https://www.wikidata.org/wiki/User:Graemebp/verification/ca/ontario

I think for statement 232277344018967

**Comment by mhl** [comment] 2018-07-11 16:35
The error here is at: https://github.com/mysociety/verification-pages/blob/a0e50cf01f39ca2ed99cba42c10767bffc235bc1/app/javascript/wikiapi.js#L478 - `result` has no `entity` element. `e.error` indicates it's a "inconsitent-language" error.

This looks like it's because the person is being created with this data:

```
{
  "labels": {
    "it": {
      "language": "it",
      "value": "Elena Pagana"
    }
  },
  "descriptions": {
    "it": {
      "language": "en",
      "value": "Italian politician"
    }
  },
  "claims": [
    {
      "mainsnak": {
        "snaktype": "value",
        "property": "P106",
        "datavalue": {
          "value": {
            "entity-type": "item",
            "numeric-id": 82955
          },
          "type": "wikibase-entityid"
        }
      },
      "type": "statement",
      "rank": "normal"
    }
  ]
}
```

I guess it's because of the `descriptions` element having an `it` key, but the language in the value object being `en`.

I think that can probably be fixed by changing the `label.lang` here to `description.lang`: https://github.com/mysociety/verification-pages/blob/a0e50cf01f39ca2ed99cba42c10767bffc235bc1/app/javascript/wikiapi.js#L450-L453

**Comment by gbp** [comment] 2018-07-12 11:17
Confirmed the same issue as diagnosed by @mhl. Just adding `checkForError` isn't enough to catch these errors so have created a new issue.

**Closed** 2018-07-12 11:21 UTC
Labels: bug
