### ISSUE TITLE
There's a position in Canada with pending transactions and a missing verification page, but the 'position' appears as a link to the Wikidata homepage

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#144] opened 2018-06-21 18:59 UTC
Mark L suspects this is caused by a malformed transaction we were sent

![image](https://user-images.githubusercontent.com/35226004/41739635-95895c24-758d-11e8-8eb1-fbe8ee7f5756.png)

**Comment by gbp** [comment] 2018-09-06 13:05
This was resolved when #420 was merged. These were caused by statements which we couldn't determine the correct position from the supplied area/membership codes in Suggestion Store https://github.com/mysociety/suggestions-store/blob/e9cdf327bc41bb5343c42ceec36ed1e0223630e5/app/decorators/suggestion_summary_decorator.rb#L20.

**Closed by gbp** 2018-09-06 13:05 UTC
Labels: Facebook suggestions, bug, next, statistics page
